export const CATEGORY_CONFIG = [
  {
    id: "radiation-safety",
    name: "Radiation Safety",
    shortName: "Radiation Safety",
    description: "ALARA, exposure limits, contamination control, and regulatory fundamentals.",
  },
  {
    id: "image-production",
    name: "Image Production",
    shortName: "Image Production",
    description: "Acquisition, processing, fusion, artifacts, and image interpretation fundamentals.",
  },
  {
    id: "instrumentation-qc",
    name: "Instrumentation & QC",
    shortName: "Instrumentation & QC",
    description: "Gamma camera physics, PET detector concepts, and routine quality control checks.",
  },
  {
    id: "clinical-procedures",
    name: "Clinical Procedures",
    shortName: "Clinical Procedures",
    description: "Patient prep, study protocols, acquisitions, and board-style procedural decisions.",
  },
  {
    id: "radiopharmaceuticals",
    name: "Radiopharmaceuticals",
    shortName: "Radiopharmaceuticals",
    description: "Generators, dose preparation, biodistribution, labeling, and assay fundamentals.",
  },
  {
    id: "patient-care",
    name: "Patient Care",
    shortName: "Patient Care",
    description: "Communication, safety screening, interventions, and pharmacologic stress knowledge.",
  },
];

export const QUESTION_BANK = [
  {
    id: "rs-01",
    category: "Radiation Safety",
    topic: "ALARA",
    type: "concept",
    difficulty: 1,
    question: "Which action best reflects the ALARA principle during routine radiopharmaceutical administration?",
    options: [
      "Minimizing time near the source and maximizing distance when feasible",
      "Repeating the survey meter check only after the procedure ends",
      "Relying on dose calibrator shielding instead of syringe shields",
      "Standing close to the patient to speed up documentation",
    ],
    answerIndex: 0,
    explanation: "ALARA focuses on lowering dose through time, distance, and shielding whenever practical.",
  },
  {
    id: "rs-02",
    category: "Radiation Safety",
    topic: "Inverse Square Law",
    type: "calculation",
    difficulty: 2,
    question: "If exposure rate is 8 mR/hr at 1 meter from a source, what is the approximate exposure rate at 2 meters?",
    options: ["16 mR/hr", "8 mR/hr", "4 mR/hr", "2 mR/hr"],
    answerIndex: 3,
    explanation: "By the inverse square law, doubling distance reduces exposure to one-fourth.",
  },
  {
    id: "rs-03",
    category: "Radiation Safety",
    topic: "Contamination Control",
    type: "protocol",
    difficulty: 3,
    question: "A technologist spills a small amount of Tc-99m on the floor. What should happen first?",
    options: [
      "Secure the area and prevent the spread of contamination",
      "Resume imaging because Tc-99m has a short half-life",
      "Document the event before performing any cleanup action",
      "Turn off the camera room power",
    ],
    answerIndex: 0,
    explanation: "The first priority is to isolate the spill and keep contamination from spreading.",
  },
  {
    id: "rs-04",
    category: "Radiation Safety",
    topic: "Exposure Monitoring",
    type: "concept",
    difficulty: 4,
    question: "A ring dosimeter is primarily used to monitor dose to which area?",
    options: ["Whole body", "Lens of the eye", "Hands and fingers", "Thyroid"],
    answerIndex: 2,
    explanation: "Extremity badges are used where the greatest occupational exposure is expected, especially the hands.",
  },
  {
    id: "rs-05",
    category: "Radiation Safety",
    topic: "Pregnancy Instructions",
    type: "protocol",
    difficulty: 5,
    question: "Which discharge instruction is most appropriate after many routine diagnostic nuclear medicine studies?",
    options: [
      "Increase hydration and void frequently unless other instructions are given",
      "Avoid all contact with family members for one week",
      "Skip all prescribed medications for 24 hours",
      "Return for a repeat injection the same day",
    ],
    answerIndex: 0,
    explanation: "Hydration and frequent voiding help reduce retained activity for many common studies.",
  },
  {
    id: "rs-06",
    category: "Radiation Safety",
    topic: "Shielding",
    type: "concept",
    difficulty: 2,
    question: "Which material is commonly used for syringe shields in nuclear medicine?",
    options: ["Lead or tungsten", "Plastic acrylic only", "Aluminum foil", "Copper mesh"],
    answerIndex: 0,
    explanation: "Lead and tungsten are commonly used to attenuate photon emissions from prepared syringes.",
  },
  {
    id: "rs-07",
    category: "Radiation Safety",
    topic: "Area Surveys",
    type: "quality-control",
    difficulty: 4,
    question: "A wipe test in the hot lab is used to evaluate which radiation safety concern?",
    options: [
      "Removable surface contamination",
      "Patient motion artifact",
      "Detector energy peaking",
      "Dose calibrator constancy drift",
    ],
    answerIndex: 0,
    explanation: "Wipe tests assess removable contamination on work surfaces and equipment.",
  },

  {
    id: "iqc-01",
    category: "Instrumentation & QC",
    topic: "Gamma Camera Physics",
    type: "concept",
    difficulty: 1,
    question: "What is the primary function of the collimator in a gamma camera?",
    options: [
      "To allow only photons traveling in selected directions to reach the crystal",
      "To amplify the electrical signal from the PMTs",
      "To store image counts before reconstruction",
      "To calibrate the dose calibrator",
    ],
    answerIndex: 0,
    explanation: "The collimator improves spatial localization by restricting the angle of accepted photons.",
  },
  {
    id: "iqc-02",
    category: "Image Production",
    topic: "Energy Window",
    type: "quality-control",
    difficulty: 2,
    question: "Why is the photopeak energy window set around the radionuclide photopeak?",
    options: [
      "To preferentially accept unscattered photons",
      "To remove the need for attenuation correction",
      "To increase room shielding",
      "To shorten the radionuclide half-life",
    ],
    answerIndex: 0,
    explanation: "Centering the window on the photopeak helps reject scatter and improve image quality.",
  },
  {
    id: "iqc-03",
    category: "Instrumentation & QC",
    topic: "Flood Uniformity",
    type: "quality-control",
    difficulty: 3,
    question: "Intrinsic flood testing is primarily performed to evaluate camera:",
    options: ["Uniformity", "Patient throughput", "Mechanical tilt", "Dose assay accuracy"],
    answerIndex: 0,
    explanation: "Flood images are a core test for detector uniformity and artifact detection.",
  },
  {
    id: "iqc-04",
    category: "Image Production",
    topic: "Center of Rotation",
    type: "quality-control",
    difficulty: 4,
    question: "Poor center-of-rotation correction in SPECT most directly causes:",
    options: [
      "Reconstruction misregistration and ring-like artifacts",
      "Increased radiopharmaceutical extravasation",
      "Incorrect syringe shield thickness",
      "Decreased Mo-99 breakthrough",
    ],
    answerIndex: 0,
    explanation: "Center-of-rotation error degrades SPECT reconstruction geometry and produces artifacts.",
  },
  {
    id: "iqc-05",
    category: "Image Production",
    topic: "Resolution Tradeoffs",
    type: "application",
    difficulty: 5,
    question: "Increasing matrix size in SPECT while keeping the same field of view generally does what?",
    options: [
      "Decreases pixel size and may improve detail at the cost of count density",
      "Increases pixel size and always lowers noise",
      "Eliminates the need for zoom",
      "Prevents attenuation artifacts",
    ],
    answerIndex: 0,
    explanation: "A larger matrix produces smaller pixels, which can improve sampling but reduces counts per pixel.",
  },
  {
    id: "iqc-06",
    category: "Instrumentation & QC",
    topic: "PET Detection",
    type: "concept",
    difficulty: 3,
    question: "PET coincidence detection is based on the near-simultaneous arrival of:",
    options: [
      "Two 511 keV photons traveling in opposite directions",
      "Two beta particles traveling in the same direction",
      "One 140 keV photon and one x-ray",
      "A positron and an annihilation neutron",
    ],
    answerIndex: 0,
    explanation: "Positron annihilation produces two 511 keV photons emitted about 180 degrees apart.",
  },
  {
    id: "iqc-07",
    category: "Instrumentation & QC",
    topic: "PMT Function",
    type: "concept",
    difficulty: 2,
    question: "Photomultiplier tubes in a scintillation camera primarily:",
    options: [
      "Convert light from the crystal into an amplified electrical signal",
      "Measure patient glucose before FDG injection",
      "Provide attenuation correction maps",
      "Determine Mo-99 breakthrough levels",
    ],
    answerIndex: 0,
    explanation: "PMTs detect scintillation light and amplify it into measurable electrical signals.",
  },

  {
    id: "rp-01",
    category: "Radiopharmaceuticals",
    topic: "Generators",
    type: "concept",
    difficulty: 1,
    question: "A Tc-99m generator is used to obtain Tc-99m from the decay of which parent radionuclide?",
    options: ["I-131", "Mo-99", "Ga-67", "Xe-133"],
    answerIndex: 1,
    explanation: "Mo-99 decays to Tc-99m, which is eluted from the generator for routine use.",
  },
  {
    id: "rp-02",
    category: "Radiopharmaceuticals",
    topic: "Dose Calibrator",
    type: "quality-control",
    difficulty: 2,
    question: "Constancy testing of a dose calibrator is commonly performed:",
    options: [
      "Daily with a long-lived reference source",
      "Only after generator elution",
      "Once per year during accreditation",
      "Only if the camera fails uniformity",
    ],
    answerIndex: 0,
    explanation: "Daily constancy verifies that the calibrator reads a stable reference source appropriately.",
  },
  {
    id: "rp-03",
    category: "Radiopharmaceuticals",
    topic: "Radiochemical Purity",
    type: "quality-control",
    difficulty: 3,
    question: "Radiochemical purity testing is performed to confirm that:",
    options: [
      "The radionuclide is bound in the intended chemical form",
      "The patient is properly hydrated",
      "The CT map is aligned with PET data",
      "The dose calibrator printer has paper",
    ],
    answerIndex: 0,
    explanation: "Radiochemical purity evaluates whether the labeled compound is present in the desired form.",
  },
  {
    id: "rp-04",
    category: "Radiopharmaceuticals",
    topic: "Half-Life",
    type: "calculation",
    difficulty: 4,
    question: "About how much activity remains after two physical half-lives have passed?",
    options: ["75%", "50%", "25%", "12.5%"],
    answerIndex: 2,
    explanation: "Each half-life reduces activity by half, so two half-lives leave one-fourth remaining.",
  },
  {
    id: "rp-05",
    category: "Radiopharmaceuticals",
    topic: "Biodistribution",
    type: "application",
    difficulty: 5,
    question: "Free pertechnetate is most likely to produce unintended uptake in which tissues?",
    options: [
      "Thyroid, salivary glands, and gastric mucosa",
      "Liver, spleen, and marrow only",
      "Renal cortex only",
      "Myocardium after stress",
    ],
    answerIndex: 0,
    explanation: "Unbound pertechnetate localizes in tissues that normally trap or secrete it, including thyroid and stomach.",
  },
  {
    id: "rp-06",
    category: "Radiopharmaceuticals",
    topic: "Labeling",
    type: "protocol",
    difficulty: 3,
    question: "Why is aseptic technique essential during radiopharmaceutical preparation?",
    options: [
      "To maintain sterility and reduce contamination risk",
      "To shorten physical half-life",
      "To change photon energy",
      "To improve SPECT reconstruction speed",
    ],
    answerIndex: 0,
    explanation: "Aseptic preparation protects product sterility and patient safety.",
  },
  {
    id: "rp-07",
    category: "Radiopharmaceuticals",
    topic: "Residual Activity",
    type: "application",
    difficulty: 2,
    question: "Measuring the syringe after injection is most helpful for determining:",
    options: [
      "Residual activity so the net administered dose can be calculated",
      "Camera linearity",
      "Patient positioning accuracy",
      "Center-of-rotation error",
    ],
    answerIndex: 0,
    explanation: "Post-injection assay helps determine how much activity was actually administered.",
  },

  {
    id: "cp-01",
    category: "Clinical Procedures",
    topic: "Hepatobiliary Imaging",
    type: "protocol",
    difficulty: 1,
    question: "For a routine hepatobiliary study, the patient is commonly instructed to be:",
    options: ["NPO for several hours beforehand", "On a clear-liquid diet for 48 hours", "Supine all night", "Off all medications for one week"],
    answerIndex: 0,
    explanation: "Fasting for several hours is standard to optimize gallbladder filling and study quality.",
  },
  {
    id: "cp-02",
    category: "Clinical Procedures",
    topic: "Bone Imaging",
    type: "protocol",
    difficulty: 2,
    question: "The delayed phase of a standard three-phase bone scan primarily reflects:",
    options: [
      "Osteoblastic activity and tracer incorporation in bone",
      "Only arterial flow",
      "Gastric emptying rate",
      "Renal filtration exclusively",
    ],
    answerIndex: 0,
    explanation: "Delayed images evaluate skeletal uptake and turnover after soft-tissue clearance.",
  },
  {
    id: "cp-03",
    category: "Clinical Procedures",
    topic: "V/Q Imaging",
    type: "application",
    difficulty: 3,
    question: "A mismatch on V/Q imaging refers to an area with:",
    options: [
      "Abnormal perfusion and relatively preserved ventilation",
      "Normal perfusion and normal ventilation",
      "Abnormal ventilation and equally abnormal perfusion only",
      "No tracer in either phase because of patient motion",
    ],
    answerIndex: 0,
    explanation: "Perfusion defects with maintained ventilation are classic for a V/Q mismatch pattern.",
  },
  {
    id: "cp-04",
    category: "Clinical Procedures",
    topic: "Renal Imaging",
    type: "application",
    difficulty: 4,
    question: "In a diuretic renogram, furosemide is used mainly to help differentiate:",
    options: [
      "Obstructive stasis from a dilated but nonobstructed collecting system",
      "Thyroiditis from Graves disease",
      "Hepatocellular dysfunction from biliary obstruction",
      "Acute cholecystitis from chronic cholecystitis",
    ],
    answerIndex: 0,
    explanation: "Diuretic challenge assesses washout and helps distinguish obstruction from nonobstructive dilation.",
  },
  {
    id: "cp-05",
    category: "Clinical Procedures",
    topic: "GI Bleed Imaging",
    type: "protocol",
    difficulty: 5,
    question: "For a tagged RBC gastrointestinal bleed study, persistent movement of activity that follows bowel anatomy suggests:",
    options: [
      "Active intraluminal bleeding",
      "Normal liver uptake",
      "Patient dehydration only",
      "Camera nonuniformity",
    ],
    answerIndex: 0,
    explanation: "True bleeding typically appears, increases, and moves in a pattern consistent with bowel transit.",
  },
  {
    id: "cp-06",
    category: "Clinical Procedures",
    topic: "Thyroid Uptake",
    type: "protocol",
    difficulty: 3,
    question: "Before a radioactive iodine uptake study, the technologist should pay special attention to recent use of:",
    options: [
      "Iodinated contrast or iodine-containing medications",
      "Topical moisturizer",
      "Oral calcium supplements only",
      "Routine saline flushes",
    ],
    answerIndex: 0,
    explanation: "Recent iodine exposure can interfere with uptake and alter study interpretation.",
  },
  {
    id: "cp-07",
    category: "Clinical Procedures",
    topic: "Gastric Emptying",
    type: "protocol",
    difficulty: 2,
    question: "Standardized meal preparation is important in gastric emptying studies because it improves:",
    options: [
      "Protocol consistency and comparability of results",
      "Crystal thickness",
      "Dose calibrator geometry",
      "PMT gain automatically",
    ],
    answerIndex: 0,
    explanation: "Using a standardized meal helps keep acquisition and interpretation consistent across patients.",
  },

  {
    id: "pc-01",
    category: "Patient Care",
    topic: "Patient Identification",
    type: "protocol",
    difficulty: 1,
    question: "Before administering a radiopharmaceutical, the technologist should confirm patient identity using:",
    options: [
      "At least two identifiers according to facility policy",
      "Room number only",
      "The study requisition only",
      "A family member's verbal confirmation only",
    ],
    answerIndex: 0,
    explanation: "Two-identifier verification is a core patient safety expectation before medication administration.",
  },
  {
    id: "pc-02",
    category: "Patient Care",
    topic: "Extravasation",
    type: "application",
    difficulty: 2,
    question: "Which issue can significantly alter quantitative accuracy on an FDG PET study if it occurs at injection?",
    options: ["Radiopharmaceutical extravasation", "Warm blankets", "Recent water intake", "Use of a larger blood pressure cuff"],
    answerIndex: 0,
    explanation: "Extravasation changes available circulating activity and can reduce quantitative reliability.",
  },
  {
    id: "pc-03",
    category: "Patient Care",
    topic: "FDG Preparation",
    type: "protocol",
    difficulty: 3,
    question: "For many FDG PET studies, elevated blood glucose is problematic because it can:",
    options: [
      "Compete with FDG uptake and reduce lesion conspicuity",
      "Improve image contrast in all tissues",
      "Remove the need for attenuation correction",
      "Shorten tracer uptake time",
    ],
    answerIndex: 0,
    explanation: "High serum glucose can compete with FDG transport and affect image quality and interpretation.",
  },
  {
    id: "pc-04",
    category: "Patient Care",
    topic: "Stress Testing",
    type: "application",
    difficulty: 4,
    question: "During pharmacologic stress testing, new wheezing after vasodilator administration should prompt the technologist to:",
    options: [
      "Alert the supervising provider immediately and follow the emergency protocol",
      "Ignore it if the ECG is normal",
      "Continue the test without documenting symptoms",
      "Send the patient to CT before telling anyone",
    ],
    answerIndex: 0,
    explanation: "Bronchospasm is a potentially important reaction and requires immediate clinical attention.",
  },
  {
    id: "pc-05",
    category: "Patient Care",
    topic: "Patient Communication",
    type: "concept",
    difficulty: 5,
    question: "The best way to reduce motion artifact in anxious patients is usually to:",
    options: [
      "Explain the procedure clearly, set expectations, and coach stillness throughout the study",
      "Skip positioning aids to save time",
      "Shorten every acquisition below protocol minimums",
      "Avoid answering patient questions until after imaging",
    ],
    answerIndex: 0,
    explanation: "Clear coaching and expectation setting often improve cooperation and image quality.",
  },
  {
    id: "pc-06",
    category: "Patient Care",
    topic: "Pregnancy Screening",
    type: "protocol",
    difficulty: 3,
    question: "Why is pregnancy screening important before many nuclear medicine procedures?",
    options: [
      "Because fetal radiation exposure should be considered before administering activity",
      "Because it determines the crystal thickness to use",
      "Because it changes how PMTs amplify light",
      "Because it removes the need for a written history",
    ],
    answerIndex: 0,
    explanation: "Pregnancy status can materially affect risk assessment and study planning.",
  },
  {
    id: "pc-07",
    category: "Image Production",
    topic: "Breathing Motion",
    type: "application",
    difficulty: 2,
    question: "When patients are unable to remain still during SPECT or PET/CT, the most likely result is:",
    options: [
      "Motion artifact and reduced interpretive confidence",
      "Automatic correction of attenuation errors",
      "Higher administered activity",
      "Improved count statistics in all frames",
    ],
    answerIndex: 0,
    explanation: "Patient motion degrades alignment and can blur or distort findings.",
  },

  {
    id: "pet-01",
    category: "Image Production",
    topic: "Physiologic Uptake",
    type: "concept",
    difficulty: 1,
    question: "Which finding is commonly considered physiologic FDG uptake?",
    options: ["Brain uptake", "Cold thyroid nodule", "Photopenic liver lesion", "Absent myocardial uptake in all patients"],
    answerIndex: 0,
    explanation: "The brain normally demonstrates high FDG uptake because of glucose metabolism.",
  },
  {
    id: "pet-02",
    category: "Image Production",
    topic: "Attenuation Correction",
    type: "application",
    difficulty: 2,
    question: "Misregistration between PET and CT can create:",
    options: [
      "Attenuation-correction artifact",
      "Dose calibrator constancy error",
      "Radiochemical impurity",
      "Mo-99 breakthrough",
    ],
    answerIndex: 0,
    explanation: "PET/CT misalignment may produce false areas of uptake or apparent defects after correction.",
  },
  {
    id: "pet-03",
    category: "Image Production",
    topic: "SUV Interpretation",
    type: "application",
    difficulty: 3,
    question: "Which factor can change SUV measurements between serial PET studies?",
    options: [
      "Differences in uptake time between injection and imaging",
      "The color map selected by the technologist alone",
      "Whether the patient wore blue clothing",
      "The order of image printing",
    ],
    answerIndex: 0,
    explanation: "SUV can vary with timing, dose, patient factors, and workflow differences.",
  },
  {
    id: "pet-04",
    category: "Image Production",
    topic: "Hybrid Imaging",
    type: "concept",
    difficulty: 4,
    question: "The main clinical advantage of hybrid PET/CT is that it combines:",
    options: [
      "Metabolic information with anatomic localization",
      "Two separate radionuclides in one syringe",
      "Planar imaging with ultrasound physics",
      "A dose calibrator and gamma counter in one device",
    ],
    answerIndex: 0,
    explanation: "PET/CT fuses functional uptake data with CT anatomy for more confident localization.",
  },
  {
    id: "pet-05",
    category: "Image Production",
    topic: "Brown Fat",
    type: "application",
    difficulty: 5,
    question: "Symmetric FDG uptake in the neck and supraclavicular regions of a cold, anxious patient most likely reflects:",
    options: ["Activated brown fat", "Diffuse skeletal metastases", "Extravasated tracer", "Patient misidentification"],
    answerIndex: 0,
    explanation: "Brown fat can show characteristic symmetric uptake, especially in cold or stimulated patients.",
  },
  {
    id: "pet-06",
    category: "Image Production",
    topic: "Cross-Sectional Correlation",
    type: "application",
    difficulty: 3,
    question: "Why is review of fused PET/CT alongside the separate PET and CT datasets important?",
    options: [
      "It helps distinguish true uptake from misregistration or CT-related artifact",
      "It changes the radionuclide half-life",
      "It removes the need for patient screening",
      "It guarantees every focus of uptake is malignant",
    ],
    answerIndex: 0,
    explanation: "Reviewing all datasets together improves confidence and helps catch registration problems.",
  },
  {
    id: "pet-07",
    category: "Image Production",
    topic: "Respiratory Motion",
    type: "application",
    difficulty: 4,
    question: "A lesion near the diaphragm may appear mismatched on fused PET/CT mainly because of:",
    options: [
      "Respiratory motion between PET and CT acquisitions",
      "Dose calibrator linearity failure",
      "Pertechnetate in the stomach",
      "Incorrect wipe test geometry",
    ],
    answerIndex: 0,
    explanation: "Respiratory motion commonly affects alignment at the lung bases and diaphragm.",
  },
];

export const IMPORT_TEMPLATE = [
  {
    id: "custom-001",
    category: "Radiation Safety",
    topic: "ALARA",
    type: "concept",
    difficulty: 2,
    question: "Sample imported question text goes here.",
    options: ["Option A", "Option B", "Option C", "Option D"],
    answerIndex: 1,
    explanation: "Brief explanation for why the correct answer is right.",
  },
];
