services:
  - type: web
    name: nuclear-medicine-boards-review
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    autoDeploy: true
    envVars:
      - key: USER_CREDENTIALS_B64
        sync: false
